### ISSUE TITLE
Separate this into template repo and private fork

### ISSUE THREAD

**Issue by LeaVerou** [madatajs/auth-serverless#8]
Our `auth.madata.dev` should be connected to the private fork, and this should be a template for people to fork that doesn't include any private keys. It is not sufficient to just remove the private keys through a commit, we need to also remove them from history. 

I'm not sure it should be an actual template repo, I don't see much benefit, and it has the downside that people cannot pull in changes from upstream. We definitely want to be able to release updates! 

I'd say this is the top priority blocker right now.

**Comment by DmitrySharabin** [comment]
Should we close it?
